---
title: "R Community & Resources"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There is no shortage of books, online tutorials, and communities that can help you get started with using R. We recommend using the following resources for help with basic to advanced R issues:

## CRAN
* [R FAQ](https://cran.r-project.org/faqs.html)
## Texts
[Introductory Statistics with R](https://www.amazon.com/gp/product/0387790535)
* [Learning R](http://shop.oreilly.com/product/0636920028352.do)
* [R Cookbook](http://shop.oreilly.com/product/9780596809164.do)
* [R for Data Science](http://shop.oreilly.com/product/0636920034407.do) *Also freely available online, see below*

## Websites & Blogs
* [RStudio - Online Learning Portal](https://www.rstudio.com/online-learning/)
* [Getting Started with R - RStudio](https://support.rstudio.com/hc/en-us/articles/201141096-Getting-Started-with-R)
* [Getting Started with R - Microsoft](https://mran.microsoft.com/documents/getting-started/)
* [UCLA Institute for Digital Research and Education - R](https://stats.idre.ucla.edu/r/)
* [R for Data Science](http://r4ds.had.co.nz/)
* [Beginner's guide to R - ComputerWorld](http://www.computerworld.com/article/2497143/business-intelligence/business-intelligence-beginner-s-guide-to-r-introduction.html)

## Q&A Sites
* [Stackoverflow](http://stackoverflow.com/questions/tagged/r)
* [R Help Listserv](https://stat.ethz.ch/mailman/listinfo/r-help)
* [RSeek Search Engine](http://rseek.org/)
* [RStudio Community](https://community.rstudio.com/)
* [R Bloggers](https://www.r-bloggers.com/)
* [Quick-R](http://www.statmethods.net/index.html)


## RStudio Cheat Sheets 
* [All Available Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/)
* [RStudio](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf)
* [Lubridate - Dates & Times](https://github.com/rstudio/cheatsheets/raw/master/lubridate.pdf)
* [Importing Data](https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf)
* [Data Transformation / dplyr](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)
* [Visualization / ggplot2](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf)

## Social Media

## Conferences and IRL Groups


